version: '3.8'

services:
  python-dev:
    image: sammrai/civitdl-webapi:latest
    volumes:
      - ./data:/data
    ports:
      - "7681:7681"
    environment:
      CIVITAI_TOKEN: ${CIVITAI_TOKEN:-''}
      MODEL_ROOT_PATH: /data
    tty: true
